### PR TITLE
Updates metatags and favicon

### PR DESCRIPTION
**Pull request by mateusortiz**

### CODE REVIEW

**Comment by mateusortiz** [comment]
cc @jaydson

**Comment by robsongajunior** [comment]
@mateusortiz the update can't be on harmonic-website, it's at **harmonic-theme-selfblog**.
This repository is the just to building theme.

**Comment by mateusortiz** [comment]
Sorry, I have already sent the commits to theme, just missing update the site.

**Comment by jaydson** [comment]
So, I'll close this PR.

**Comment by UltCombo** [comment]
So we need to push a new build. Isn't this PR the result of a build?

**Comment by mateusortiz** [comment]
Yeah, it's the result of some updates to the template.

**Comment by UltCombo** [comment]
@robsongajunior @jaydson This PR is the result of running `harmonic build`. Shouldn't this be merged?

**Comment by jaydson** [comment]
Yes, you're right @UltCombo.
It was a misunderstanding.

**Comment by UltCombo** [comment]
Thanks @mateusortiz !

**Pull request merged**
